FROM node:20.9.0 AS builder

# Establece el directorio de trabajo en el contenedor
WORKDIR /app


# Copia los archivos de dependencias de Node.js
COPY package*.json ./
COPY . .

RUN npm install

# Expone el puerto 80
EXPOSE 80

# Inicia la aplicación
CMD ["npm", "run", "dev"]