version: '3.8'
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
   
    ports:
      - '84:80'

    volumes:
      - /app/node_modules
      - .:/app

  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod

    ports:
      - '85:8080'

    volumes:
      - /app/node_modules
      - ./server:/app

   